apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: batman-vm-ops
  namespace: batman
rules:
  # Читать ВМ и их состояние
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines","virtualmachineinstances"]
    verbs: ["get","list","watch"]

  # Разрешить только start/stop ВМ (без edit/patch/delete)
  - apiGroups: ["kubevirt.io"]
    resources:
      - "virtualmachines/start"
      - "virtualmachines/stop"
    verbs: ["update"]

  # (необязательно) Читать события и PVC, чтобы в UI всё было видно
  - apiGroups: [""]
    resources: ["events","persistentvolumeclaims"]
    verbs: ["get","list","watch"]
