apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: batman-view
  namespace: batman
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: User
    name: batman